name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter_callkit_incoming: 1.0.2+2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.7.0
  http: ^0.13.0
  uuid: ^3.0.7

dependency_overrides:
  plugin_platform_interface: ^2.1.3

flutter:
  uses-material-design: true
